import { User, Category, Article, UserRole, ArticleStatus, Notification, NotificationType, Subscriber } from './types';

export let users: User[] = [
  {
    id: 'u1',
    name: 'நிர்வாக பயனர்',
    email: 'admin@vadali.com',
    password: '$2b$10$P3D8gs2qo5yk9S3nh9y73O6tmDi2yCp6ZjozGIsJTKN0H7Ezao4bC',
    role: UserRole.ADMIN,
    avatarUrl: 'https://picsum.photos/seed/u1/100/100',
    bio: 'Responsible for site administration and content oversight.'
  },
  { id: 'u2', name: 'ஆசிரியர் எரிக்கா', email: 'editor@news.com', role: UserRole.EDITOR, avatarUrl: 'https://picsum.photos/seed/u2/100/100', bio: 'Experienced editor with a keen eye for detail and a passion for quality journalism.' },
  { id: 'u3', name: 'ஆசிரியர் அருண்', email: 'author@news.com', role: UserRole.AUTHOR, avatarUrl: 'https://picsum.photos/seed/u3/100/100', bio: 'Technology correspondent covering AI, machine learning, and innovation.' },
  { id: 'u4', name: 'செய்தியாளர் ரீட்டா', email: 'reporter@news.com', role: UserRole.AUTHOR, avatarUrl: 'https://picsum.photos/seed/u4/100/100', bio: 'Financial reporter specializing in global markets and economic policy.' },
  { id: 'u5', name: 'ஆசிரியர் பிரியா', email: 'editor2@news.com', role: UserRole.EDITOR, avatarUrl: 'https://picsum.photos/seed/u5/100/100', bio: 'Lead editor for the politics and world news sections.' },
  { id: 'u6', name: 'கட்டுரையாளர் ரவி', email: 'author2@news.com', role: UserRole.AUTHOR, avatarUrl: 'https://picsum.photos/seed/u6/100/100', bio: 'Investigative journalist with a focus on environmental and climate change stories.' },
  { id: 'u7', name: 'நிருபர் சுனிதா', email: 'reporter2@news.com', role: UserRole.AUTHOR, avatarUrl: 'https://picsum.photos/seed/u7/100/100', bio: 'Entertainment and cinema critic, following the latest trends in the film industry.' },
];

export let categories: Category[] = [
  { id: 'c1', name: 'Technology', slug: 'technology' },
  { id: 'c2', name: 'Business', slug: 'business' },
  { id: 'c3', name: 'Politics', slug: 'politics' },
  { id: 'c4', name: 'Sports', slug: 'sports' },
  { id: 'c5', name: 'Health', slug: 'health' },
  { id: 'c6', name: 'World', slug: 'world' },
  { id: 'c7', name: 'Cinema', slug: 'cinema' },
  { id: 'c8', name: 'Lifestyle', slug: 'lifestyle' },
  { id: 'c9', name: 'Science', slug: 'science' },
];

export let articles: Article[] = [
  // Published Articles (More for homepage)
  {
    id: 'a1',
    title: 'செயற்கை நுண்ணறிவின் எதிர்காலம்: 2024 இல் கவனிக்க வேண்டிய போக்குகள்',
    slug: 'future-of-ai-2024',
    summary: 'செயற்கை நுண்ணறிவு முன்னெப்போதும் இல்லாத வேகத்தில் வளர்ந்து வருகிறது. இந்த ஆண்டு தொழில்துறையை வடிவமைக்கும் முக்கிய போக்குகள் இங்கே.',
    content: '<p>செயற்கை நுண்ணறிவு (AI) உலகம் நிலையான மாற்றத்தில் உள்ளது. நாம் 2024 இல் மேலும் முன்னேறும்போது, தொழில்களையும் நமது அன்றாட வாழ்க்கையையும் மறுவரையறை செய்வதாக உறுதியளிக்கும் பல முக்கிய போக்குகள் வெளிவருகின்றன...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a1/800/400',
    authorId: 'u3',
    categoryId: 'c1',
    tags: ['AI', 'இயந்திர கற்றல்', 'புத்தாக்கம்'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-22T10:00:00Z',
    views: 25203,
    isFeatured: true,
    comments: [
      { id: 'com1', authorName: 'தொழில்நுட்ப ஆர்வலர்', authorAvatarUrl: 'https://picsum.photos/seed/com1/50/50', text: 'சிறந்த கண்ணோட்டம்!', date: '2024-07-22T12:30:00Z', status: 'APPROVED' },
    ],
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ'
  },
  {
    id: 'a2',
    title: 'புதிய பொருளாதாரக் கொள்கைகளுக்கு உலகச் சந்தைகள் எதிர்வினை',
    slug: 'global-markets-react',
    summary: 'சமீபத்திய கொள்கை மாற்றங்கள் வோல் ஸ்ட்ரீட் முதல் டோக்கியோ வரை உலகெங்கிலும் உள்ள பங்குச் சந்தைகளை எவ்வாறு பாதிக்கின்றன என்பது குறித்த ஆழமான பார்வை.',
    content: '<p>கடந்த வாரம் அறிவிக்கப்பட்ட புதிய வர்த்தக ஒப்பந்தங்களின் சிற்றலை விளைவுகளை ஆய்வாளர்கள் உன்னிப்பாகக் கண்காணித்து வருகின்றனர்...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a2/800/400',
    authorId: 'u4',
    categoryId: 'c2',
    tags: ['பொருளாதாரம்', 'பங்குச் சந்தை', 'நிதி'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-22T09:30:00Z',
    views: 18904,
    comments: [
       { id: 'com2', authorName: 'பொருளாதார நிபுணர்', authorAvatarUrl: 'https://picsum.photos/seed/com2/50/50', text: 'This needs further clarification.', date: '2024-07-23T11:00:00Z', status: 'PENDING' },
       { id: 'com3', authorName: 'மாணவர்', authorAvatarUrl: 'https://picsum.photos/seed/com3/50/50', text: 'Could you explain the impact on emerging markets?', date: '2024-07-23T11:05:00Z', status: 'PENDING' },
    ],
  },
  {
    id: 'a5',
    title: 'மருத்துவத்தில் திருப்புமுனை: நோயாளிகளுக்கு ஒரு புதிய நம்பிக்கை',
    slug: 'medical-breakthrough-hope',
    summary: 'ஒரு பெரிய நோய்க்கான சிகிச்சை நிலப்பரப்பை மாற்றக்கூடிய ஒரு குறிப்பிடத்தக்க கண்டுபிடிப்பை விஞ்ஞானிகள் அறிவித்துள்ளனர்.',
    content: '<p>"ஜர்னல் ஆஃப் மெடிசின்" இல் இன்று வெளியிடப்பட்ட ஒரு அற்புதமான ஆய்வு, ஆரம்பகால சோதனைகளில் குறிப்பிடத்தக்க வெற்றியைக் காட்டிய ஒரு புதிய சிகிச்சை முறையை விவரிக்கிறது...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a5/800/400',
    authorId: 'u3',
    categoryId: 'c5',
    tags: ['மருத்துவம்', 'உடல்நலம்', 'ஆராய்ச்சி'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-22T08:00:00Z',
    views: 29489,
    isFeatured: true,
    comments: [],
  },
  {
    id: 'a7',
    title: 'உலகளாவிய காலநிலை மாநாடு முக்கிய முடிவுகளுடன் நிறைவடைகிறது',
    slug: 'global-climate-summit-concludes',
    summary: 'காலநிலை மாற்றத்தை எதிர்ப்பதற்கான புதிய ஒப்பந்தங்கள் மற்றும் வாக்குறுதிகளுடன் உலகத் தலைவர்கள் தங்கள் பேச்சுவார்த்தைகளை முடிக்கின்றனர்.',
    content: '<p>பல வார தீவிர விவாதங்களுக்குப் பிறகு, உலகளாவிய காலநிலை மாநாடு கார்பன் உமிழ்வைக் குறைப்பதற்கும் பசுமை ஆற்றல் முயற்சிகளுக்கு நிதியளிப்பதற்கும் ஒருமித்த கருத்துடன் முடிவுக்கு வந்தது...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a7/800/400',
    authorId: 'u6',
    categoryId: 'c6',
    tags: ['காலநிலை மாற்றம்', 'உலகளாவிய நிகழ்வுகள்', 'சுற்றுச்சூழல்'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-21T18:00:00Z',
    views: 16432,
    comments: [],
  },
  {
    id: 'a8',
    title: 'பிளாக்பஸ்டர் திரைப்படம் பாக்ஸ் ஆபிஸ் சாதனைகளை முறியடிக்கிறது',
    slug: 'blockbuster-movie-breaks-records',
    summary: 'சமீபத்திய சூப்பர் ஹீரோ திரைப்படம் அதன் தொடக்க வார இறுதியில் உலகளவில் $500 மில்லியனைத் தாண்டி, எல்லா எதிர்பார்ப்புகளையும் மீறுகிறது.',
    content: '<p>திரைப்படத் துறையில் ஒரு குறிப்பிடத்தக்க சாதனையாக, "கேலக்ஸி கார்டியன்ஸ் ரிட்டர்ன்" திரைப்படம் வரலாறு படைத்துள்ளது. அதன் அற்புதமான காட்சிகள் மற்றும் வசீகரிக்கும் கதைக்களத்துடன்...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a8/800/400',
    authorId: 'u7',
    categoryId: 'c7',
    tags: ['சினிமா', 'திரைப்படங்கள்', 'பொழுதுபோக்கு'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-21T15:00:00Z',
    views: 35123,
    isFeatured: true,
    comments: [],
  },
  {
    id: 'a9',
    title: 'விளையாட்டுப் போட்டியில் எதிர்பாராத வெற்றி: இறுதி நிமிட கோல் ஆட்டத்தை முடிவு செய்தது',
    slug: 'championship-final-last-minute-goal',
    summary: 'ஒரு பரபரப்பான இறுதிப் போட்டியில், கடைசி நிமிடத்தில் அடிக்கப்பட்ட கோல் உள்ளூர் அணிக்கு சாம்பியன்ஷிப் பட்டத்தை வென்று தந்தது.',
    content: '<p>ஆயிரக்கணக்கான ரசிகர்கள் முன்னிலையில், கால்பந்து சாம்பியன்ஷிப் இறுதிப் போட்டி ஒரு மறக்க முடியாத தருணத்தைக் கண்டது. ஆட்டம் சமநிலையில் இருந்தபோது, ஒரு அற்புதமான கோல்...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a9/800/400',
    authorId: 'u4',
    categoryId: 'c4',
    tags: ['கால்பந்து', 'விளையாட்டு', 'சாம்பியன்ஷிப்'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-21T12:00:00Z',
    views: 21550,
    comments: [],
  },
  {
    id: 'a10',
    title: 'செவ்வாய் கிரகத்தில் நீர் இருப்பதற்கான புதிய ஆதாரங்களை நாசா கண்டுபிடித்தது',
    slug: 'nasa-finds-new-evidence-of-water-on-mars',
    summary: 'செவ்வாய் கிரகத்தின் மேற்பரப்பிற்கு அடியில் உறைந்த நீர் ஏரிகள் இருப்பதற்கான வலுவான ஆதாரங்களை நாசாவின் ரோவர் அனுப்பியுள்ளது.',
    content: '<p>விண்வெளி ஆராய்ச்சியில் ஒரு முக்கிய மைல்கல்லாக, செவ்வாய் கிரகத்தில் உயிர்கள் வாழ்வதற்கான சாத்தியக்கூறுகள் குறித்த புதிய நம்பிக்கையை நாசாவின் கண்டுபிடிப்புகள் தூண்டியுள்ளன...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a10/800/400',
    authorId: 'u6',
    categoryId: 'c9',
    tags: ['விண்வெளி', 'நாசா', 'அறிவியல்'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-20T11:00:00Z',
    views: 19876,
    comments: [],
  },
  {
    id: 'a11',
    title: 'ஆரோக்கியமான வாழ்க்கை முறைக்கான 5 எளிய குறிப்புகள்',
    slug: '5-tips-for-healthy-lifestyle',
    summary: 'உங்கள் அன்றாட வாழ்க்கையில் சிறிய மாற்றங்களைச் செய்வதன் மூலம் உங்கள் ஒட்டுமொத்த ஆரோக்கியத்தையும் நல்வாழ்வையும் மேம்படுத்தலாம்.',
    content: '<p>சமச்சீர் உணவு, வழக்கமான உடற்பயிற்சி மற்றும் போதுமான தூக்கம் ஆகியவை ஆரோக்கியமான வாழ்க்கைக்கு அவசியம். இந்த கட்டுரையில், நீங்கள் பின்பற்றக்கூடிய எளிய மற்றும் பயனுள்ள குறிப்புகள் கொடுக்கப்பட்டுள்ளன...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a11/800/400',
    authorId: 'u3',
    categoryId: 'c8',
    tags: ['வாழ்க்கை முறை', 'ஆரோக்கியம்', 'குறிப்புகள்'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-20T09:00:00Z',
    views: 45001,
    isFeatured: true,
    comments: [],
  },
  {
    id: 'a12',
    title: 'புதிய ஸ்மார்ட்போன் வெளியீடு: தொழில்நுட்ப உலகில் ஒரு புதிய புரட்சி',
    slug: 'new-smartphone-revolution',
    summary: 'முன்னணி தொழில்நுட்ப நிறுவனம் தனது புதிய முதன்மை ஸ்மார்ட்போனை வெளியிட்டுள்ளது, இது மேம்பட்ட கேமரா மற்றும் நீண்ட பேட்டரி ஆயுளைக் கொண்டுள்ளது.',
    content: '<p>தொழில்நுட்ப ஆர்வலர்கள் ஆவலுடன் எதிர்பார்த்த புதிய "கேலக்ஸி எக்ஸ்" ஸ்மார்ட்போன் இன்று வெளியிடப்பட்டது. இதன் அம்சங்கள் மற்றும் விலை விவரங்களை இங்கே காணலாம்...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a12/800/400',
    authorId: 'u7',
    categoryId: 'c1',
    tags: ['ஸ்மார்ட்போன்', 'தொழில்நுட்பம்', 'வெளியீடு'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-19T16:00:00Z',
    views: 12345,
    comments: [],
  },
  {
    id: 'a13',
    title: 'தேர்தல் களம் சூடுபிடிக்கிறது: முக்கிய கட்சிகள் பிரச்சாரத்தை தீவிரப்படுத்துகின்றன',
    slug: 'election-campaign-intensifies',
    summary: 'வரவிருக்கும் தேர்தலை முன்னிட்டு, அரசியல் கட்சிகள் தங்கள் தேர்தல் அறிக்கைகளை வெளியிட்டு, நாடு தழுவிய பிரச்சாரத்தில் ஈடுபட்டுள்ளன.',
    content: '<p>வாக்குப்பதிவு நெருங்கி வருவதால், அரசியல் களம் பரபரப்பாக காணப்படுகிறது. தலைவர்கள் பொதுக்கூட்டங்கள் மற்றும் பேரணிகளில் ஈடுபட்டு வாக்காளர்களைக் கவர முயற்சிக்கின்றனர்...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a13/800/400',
    authorId: 'u4',
    categoryId: 'c3',
    tags: ['அரசியல்', 'தேர்தல்', 'செய்திகள்'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-19T11:00:00Z',
    views: 9876,
    comments: [],
  },
  {
    id: 'a14',
    title: 'ஸ்டார்ட்அப் நிறுவனங்களுக்கு புதிய முதலீடுகள்: தொழில்முனைவோருக்கு ஊக்கம்',
    slug: 'startup-funding-boost',
    summary: 'இந்திய ஸ்டார்ட்அப் சூழல் ஒரு பெரிய ஊக்கத்தைப் பெறுகிறது, ஏனெனில் துணிகர மூலதன நிறுவனங்கள் புதுமையான யோசனைகளில் மில்லியன் கணக்கான டாலர்களை முதலீடு செய்கின்றன.',
    content: '<p>தொழில்நுட்பம், சுகாதாரம் மற்றும் நிதிச் சேவைத் துறைகளில் உள்ள பல இளம் நிறுவனங்கள் குறிப்பிடத்தக்க நிதியுதவியைப் பெற்றுள்ளன. இது நாட்டின் பொருளாதார வளர்ச்சிக்கு பங்களிக்கும் என எதிர்பார்க்கப்படுகிறது...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a14/800/400',
    authorId: 'u6',
    categoryId: 'c2',
    tags: ['ஸ்டார்ட்அப்', 'வணிகம்', 'முதலீடு'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-18T14:00:00Z',
    views: 7500,
    comments: [],
  },

  // Advertisement Articles
  {
    id: 'ad1',
    title: 'உங்கள் கனவு இல்லம்: புதிய அடுக்குமாடி குடியிருப்புகள் விற்பனைக்கு',
    slug: 'dream-home-apartments-sale',
    summary: 'சென்னையின் மையத்தில் நவீன வசதிகளுடன் கூடிய சொகுசு வீடுகள். இன்றே முன்பதிவு செய்யுங்கள்!',
    content: '<p>உங்கள் வாழ்க்கை முறையை மேம்படுத்தும் வகையில் வடிவமைக்கப்பட்ட எங்களின் புதிய திட்டத்தை அறிமுகப்படுத்துகிறோம். நீச்சல் குளம், உடற்பயிற்சி கூடம் மற்றும் 24/7 பாதுகாப்பு போன்ற வசதிகளுடன்...</p>',
    coverImageUrl: 'https://picsum.photos/seed/ad1/800/400',
    authorId: 'u1', 
    categoryId: 'c8',
    tags: ['ரியல் எஸ்டேட்', 'முதலீடு', 'சென்னை'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-22T11:00:00Z',
    views: 5000,
    comments: [],
    isAdvertisement: true,
  },
  {
    id: 'ad2',
    title: 'புதிய டெக்னோ மொபைல்: அசத்தலான அம்சங்களுடன் அறிமுகம்',
    slug: 'new-techno-mobile-launch',
    summary: '5G வேகம், 108MP கேமரா மற்றும் நீண்ட நேர பேட்டரி ஆயுள். நம்பமுடியாத விலையில்!',
    content: '<p>டெக்னோவின் சமீபத்திய ஸ்மார்ட்போன் மூலம் தொழில்நுட்பத்தின் அடுத்த கட்டத்தை அனுபவியுங்கள். இது உங்கள் புகைப்படம் எடுக்கும் மற்றும் கேமிங் அனுபவத்தை மாற்றியமைக்கும்...</p>',
    coverImageUrl: 'https://picsum.photos/seed/ad2/800/400',
    authorId: 'u1',
    categoryId: 'c1',
    tags: ['மொபைல்', 'தொழில்நுட்பம்', 'விமர்சனம்'],
    status: ArticleStatus.PUBLISHED,
    publishedAt: '2024-07-21T14:00:00Z',
    views: 8500,
    comments: [],
    isAdvertisement: true,
  },

  // Non-Published Articles
  {
    id: 'a3',
    title: 'தி அண்டர்டாக் ஸ்டோரி: உள்ளூர் அணி எப்படி சாம்பியன்ஷிப்பை வென்றது',
    slug: 'underdog-championship-win',
    summary: 'விடாமுயற்சி மற்றும் குழுப்பணியின் எழுச்சியூட்டும் கதை.',
    content: '<p>அவர்கள் வெற்றி பெறுவார்கள் என்று யாரும் எதிர்பார்க்கவில்லை...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a3/800/400',
    authorId: 'u3',
    categoryId: 'c4',
    tags: ['கூடைப்பந்து', 'சாம்பியன்ஷிப்', 'உத்வேகம்'],
    status: ArticleStatus.PENDING_REVIEW,
    publishedAt: null,
    views: 0,
    comments: [],
  },
  {
    id: 'a4',
    title: 'வரைவு: வரவிருக்கும் தேர்தல் குறித்த ஆரம்ப எண்ணங்கள்',
    slug: 'draft-election-thoughts',
    summary: 'அரசியல் பந்தயத்தை வடிவமைக்கும் வேட்பாளர்கள் மற்றும் முக்கிய பிரச்சினைகள் பற்றிய ஒரு பூர்வாங்க பார்வை.',
    content: '<p>இது ஒரு வரைவு மற்றும் வெளியீட்டிற்கு தயாராக இல்லை...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a4/800/400',
    authorId: 'u4',
    categoryId: 'c3',
    tags: ['அரசியல்', 'தேர்தல்'],
    status: ArticleStatus.DRAFT,
    publishedAt: null,
    views: 0,
    comments: [],
  },
  {
    id: 'a6',
    title: 'தொற்றுநோய்க்குப் பிந்தைய பணியிடத்தில் வழிசெலுத்தல்',
    slug: 'post-pandemic-workplace',
    summary: 'நிறுவனங்கள் கலப்பின மாதிரிகளுடன் பரிசோதனை செய்கின்றன.',
    content: '<p>ஒரு கனசதுரத்தில் ஒன்பது முதல் ஐந்து வரை என்பது பலருக்கு ஒரு நினைவுச்சின்னம்...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a6/800/400',
    authorId: 'u4',
    categoryId: 'c2',
    tags: ['வேலை', 'வணிகம்', 'வேலையின் எதிர்காலம்'],
    status: ArticleStatus.REJECTED,
    publishedAt: null,
    views: 0,
    comments: [],
    rejectionReason: 'Needs more specific data and sources to support the claims.'
  },
  {
    id: 'a15',
    title: 'நகர்ப்புற தோட்டக்கலை: சிறிய இடங்களில் உங்கள் சொந்த உணவை வளர்ப்பது',
    slug: 'urban-gardening-guide',
    summary: 'பால்கனிகள் மற்றும் ஜன்னல் ஓரங்களில் காய்கறிகள் மற்றும் மூலிகைகளை வளர்ப்பதற்கான ஒரு தொடக்க வழிகாட்டி.',
    content: '<p>இடப் பற்றாக்குறை ஒரு தடையாக இருக்க வேண்டியதில்லை. இந்த வழிகாட்டி உங்கள் சொந்த சமையலறை தோட்டத்தை அமைக்க உதவும்...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a15/800/400',
    authorId: 'u7',
    categoryId: 'c8',
    tags: ['தோட்டக்கலை', 'வாழ்க்கை முறை', 'DIY'],
    status: ArticleStatus.PENDING_REVIEW,
    publishedAt: null,
    views: 0,
    comments: [],
  },
  {
    id: 'a16',
    title: 'வரைவு: புதிய கேமிங் கன்சோல் பற்றிய முதல் பதிவுகள்',
    slug: 'draft-gaming-console-review',
    summary: 'வரவிருக்கும் "பிளேஸ்டேஷன் 6" பற்றிய ஆரம்பகட்ட சிந்தனைகள் மற்றும் வதந்திகள்.',
    content: '<p>இன்னும் உறுதிப்படுத்தப்படவில்லை, ஆனால் கசிவுகள் ஒரு சக்திவாய்ந்த புதிய சிப் மற்றும் அதிவேக கிராபிக்ஸ் ஆகியவற்றைக் குறிப்பிடுகின்றன...</p>',
    coverImageUrl: 'https://picsum.photos/seed/a16/800/400',
    authorId: 'u3',
    categoryId: 'c1',
    tags: ['கேமிங்', 'தொழில்நுட்பம்'],
    status: ArticleStatus.DRAFT,
    publishedAt: null,
    views: 0,
    comments: [],
  },
];

export let notifications: Notification[] = [
    {
        id: 'n1',
        userId: 'u3', // அருண்
        articleId: 'a1',
        message: 'Congratulations! Your article "செயற்கை நுண்ணறிவின் எதிர்காலம்: 2024 இல் கவனிக்க வேண்டிய போக்குகள்" has been approved and published.',
        type: NotificationType.APPROVED,
        read: false,
        timestamp: '2024-07-22T10:05:00Z',
    },
    {
        id: 'n2',
        userId: 'u4', // ரீட்டா
        articleId: 'a6',
        message: 'Your article "தொற்றுநோய்க்குப் பிந்தைய பணியிடத்தில் வழிசெலுத்தல்" has been rejected. Reason: Needs more specific data and sources.',
        type: NotificationType.REJECTED,
        read: false,
        timestamp: '2024-07-21T14:00:00Z',
    },
    {
        id: 'n3',
        userId: 'u3', // அருண்
        articleId: 'a3',
        message: 'A new comment was posted on your article "தி அண்டர்டாக் ஸ்டோரி: உள்ளூர் அணி எப்படி சாம்பியன்ஷிப்பை வென்றது".',
        type: NotificationType.COMMENT,
        read: true,
        timestamp: '2024-07-23T09:15:00Z',
    },
    {
        id: 'n4',
        userId: 'u4', // ரீட்டா
        articleId: 'a2',
        message: 'Congratulations! Your article "புதிய பொருளாதாரக் கொள்கைகளுக்கு உலகச் சந்தைகள் எதிர்வினை" has been approved and published.',
        type: NotificationType.APPROVED,
        read: true,
        timestamp: '2024-07-22T09:35:00Z',
    },
];

export let subscribers: Subscriber[] = [
    { id: 'sub1', email: 'reader1@example.com', subscribedAt: '2024-07-20T10:00:00Z' },
    { id: 'sub2', email: 'newsfan@example.com', subscribedAt: '2024-07-21T11:30:00Z' },
    { id: 'sub3', email: 'johndoe@example.com', subscribedAt: '2024-07-22T15:00:00Z' },
    { id: 'sub4', email: 'test.user@example.com', subscribedAt: '2024-07-23T09:00:00Z' },
];